# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6a48edcab9c92216e00df828962cc175dd5d45040ad137ac3d4f4652fbea3b634dca2ee8efa05776eb1e6a1712fda5210670e766e314c026df54dce8e70bfa2

test:
  secret_key_base: d81d4c0507fd6a44c3e92e8d13f62e3f65019e7fbdd79f4ec068159a4a9f8a84c088cd64b9aa8adbd047f71c8fae9e38c8d26f902dfcf1dc4361fef519899c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
